services:

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker/app/prod.env 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5